# Generated by Django 5.0.4 on 2024-05-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=20, verbose_name='Dirección')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_descuento', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
