# Generated by Django 5.0.4 on 2024-05-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='creado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='nopass', max_length=500, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password_decode',
            field=models.CharField(max_length=500, null=True, verbose_name='Password_Hash'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(default='USER', max_length=20, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=15, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=20, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='telefono'),
        ),
    ]
