# Generated by Django 5.0.4 on 2024-05-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='imagen')),
            ],
        ),
    ]
