# Generated by Django 5.0.4 on 2024-06-18 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(primary_key=True, serialize=False, verbose_name='id_producto')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.categoria', verbose_name='categoria')),
            ],
        ),
    ]
