# Generated by Django 5.0.4 on 2024-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='id_producto'),
        ),
    ]
