# Generated by Django 5.0.4 on 2024-06-27 01:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupones', '0001_initial'),
        ('gestionPedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('direccion', models.CharField(max_length=200, verbose_name='direccion')),
                ('comuna', models.CharField(max_length=50, verbose_name='comuna')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('telefono', models.CharField(default=0, max_length=12, verbose_name='telefono')),
                ('comentario', models.CharField(blank=True, max_length=500, verbose_name='comentario')),
                ('subtotal', models.IntegerField(verbose_name='subtotal')),
                ('descuento', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='descuento')),
                ('total_oc', models.IntegerField(default=0, verbose_name='total_oc')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('cupon', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='cupones.cupon', verbose_name='cupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden', verbose_name='orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.producto', verbose_name='orden_productos')),
            ],
        ),
    ]
