# Generated by Django 5.0.4 on 2024-06-20 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionPedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30, verbose_name='nombre')),
                ('apellido', models.TextField(max_length=50, verbose_name='apellido')),
                ('direccion', models.TextField(max_length=200, verbose_name='direccion')),
                ('comuna', models.TextField(max_length=50, verbose_name='comuna')),
                ('ciudad', models.TextField(max_length=50, verbose_name='ciudad')),
                ('telefono', models.TextField(default=0, max_length=12, verbose_name='telefono')),
                ('comentario', models.TextField(blank=True, max_length=500, verbose_name='comentario')),
                ('total_oc', models.IntegerField(default=0, verbose_name='total_oc')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden', verbose_name='orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPedidos.producto', verbose_name='orden_productos')),
            ],
        ),
    ]
