# Generated by Django 5.0.4 on 2024-06-21 02:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cupones.cupon', verbose_name='cupon'),
        ),
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='ciudad',
            field=models.CharField(max_length=50, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, verbose_name='comentario'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='comuna',
            field=models.CharField(max_length=50, verbose_name='comuna'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='telefono',
            field=models.CharField(default=0, max_length=12, verbose_name='telefono'),
        ),
    ]
