# Generated by Django 5.0.4 on 2024-06-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, verbose_name='descuento'),
        ),
    ]
