# Generated by Django 5.0.4 on 2024-06-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='correo',
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono',
            field=models.TextField(default=0, max_length=12, verbose_name='telefono'),
        ),
    ]
