# Generated by Django 5.0.4 on 2024-06-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_remove_orden_correo_orden_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='total_oc',
        ),
    ]
