# Generated by Django 5.0.4 on 2024-06-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
        ('ordenes', '0002_orden_cupon_orden_descuento_alter_orden_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='cupon',
        ),
        migrations.AddField(
            model_name='orden',
            name='cupon',
            field=models.ManyToManyField(blank=True, default=False, to='cupones.cupon', verbose_name='cupon'),
        ),
    ]
