# Generated by Django 5.0.4 on 2024-07-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_orden_cupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'get_latest_by': 'id', 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vci', models.CharField(max_length=5, verbose_name='VCI')),
                ('status', models.CharField(max_length=65, verbose_name='status')),
                ('buy_order', models.CharField(max_length=27, verbose_name='num_trans')),
                ('session_id', models.CharField(max_length=62, verbose_name='id_session')),
                ('card_number', models.CharField(max_length=19, verbose_name='num_tarjeta')),
                ('accouting_date', models.CharField(max_length=4, verbose_name='fecha_trans')),
                ('authorization_code', models.CharField(max_length=7, verbose_name='cod_auth')),
                ('payment_type_code', models.CharField(max_length=3, verbose_name='tipo_pago')),
                ('response_code', models.CharField(max_length=3, verbose_name='cod_respuesta')),
                ('installments_number', models.CharField(max_length=3, verbose_name='num_cuotas')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
