# Generated by Django 5.0.4 on 2024-06-25 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_remove_orden_descuento_remove_orden_cupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
