# Generated by Django 5.0.4 on 2024-07-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_alter_orden_options_transaccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='accouting_date',
            new_name='accounting_date',
        ),
    ]
