# Generated by Django 5.0.4 on 2024-07-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_rename_accouting_date_transaccion_accounting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='card_number',
            field=models.CharField(verbose_name='num_tarjeta'),
        ),
    ]
